name: "MyFramework watchOS CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["OS=6.0,name=Apple Watch Series 5 - 44mm"] #, "OS=4.2,name=Apple Watch Series 3 - 42mm", "OS=3.2,name=Apple Watch Series 2 - 42mm"]
    env:
      MINT_PATH: Mint
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: Mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mint/metadata.json') }}
          restore-keys: |
            ${{ runner.os }}-mint-
      - name: Bootstrap
        run: make first_install
      - name: iOS - ${{ matrix.destination }}
        run: |
            set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "MyFramework.xcodeproj" -scheme "MyFramework_watchOS" -destination "${{ matrix.destination }}" clean | xcpretty
